### ISSUE TITLE
pretrained network

### ISSUE THREAD

**Issue by Florian-Barthel** [hse1032/GSGAN#2]
Hi Sangeek Hyun and Jae-Pil Heo,

very impressive work! Is is possible for you to provide a pretrained model checkpoint for the results that you report in your paper?

**Comment by hse1032** [comment]
We are planning to release our checkpoint soon, so please stay tuned!

**Comment by hse1032** [comment]
We have just uploaded pre-trained checkpoints in google drive,
and attach the link in README.

Thank you for your interests again!
